package com.kle.code.dao;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.Date;

@Mapper
public interface TeachMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("sid") Integer sid, @Param("tid") Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach
     *
     * @mbggenerated
     */
    int insert(@Param("sid") Integer sid, @Param("tid") Integer tid, @Param("createTime") Date createTime);

}