package com.kle.code.dao;

import com.kle.code.model.Student;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Map;

@Mapper
public interface TeachMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("sid") Integer sid, @Param("tid") Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach
     *
     * @mbggenerated
     */
    int insert(@Param("sid") Integer sid, @Param("tid") Integer tid, @Param("createTime") Date createTime);

}